name: Docker push - Raw Material Microservice

on:
  push:
    branches:
      - dev
    paths:
      - 'inventory-rawmaterial-order-service/**'

defaults:
  run:
    working-directory: inventory-rawmaterial-order-service

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Compile code
        run: mvn compile
  #   test:
  #     runs-on: ubuntu-latest
  #     name: Running tests
  #     needs: compile
  #     steps:
  #       - uses: actions/checkout@v2
  #       - name: Set up JDK 1.8
  #         uses: actions/setup-java@v1
  #         with:
  #           java-version: 1.8
  #       - name: Run unit tests
  #         run: mvn test
  build-and-deploy:
    runs-on: ubuntu-latest
    name: Build and Push to Docker
    needs: compile
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Build
        run: mvn clean package -DskipTests
      - name: Set env
        run: echo "NOW=v$(date +'%Y%m%d.%H%M%S')" >> $GITHUB_ENV
        # Required for Build and push step
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        # Required for Build and push step
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        # Required for Build and push step
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: inventory-rawmaterial-order-service
          file: inventory-rawmaterial-order-service/Dockerfile
          push: true
          tags: |
            gagandeep39/inventory-rawmaterial-order-service:${{env.NOW}}
            gagandeep39/inventory-rawmaterial-order-service:latest
